### ISSUE TITLE
Inconsistencies with MonoDevelop flatpak & GTK#

### ISSUE THREAD

**Issue by define-private-public** [mono/monodevelop#3539]
I'm running Ubuntu 16.04 and tried out the new flatpak MonoDevelop.  While I can create new GTK# 2.0 apps via the New Project Wizard, it's showing the references with a red X next to them.  If I also try to create a new empty/console project and add the `GtkSharp` package, it's not able to build the project, since it's not able to get a reference assembly to `Object`.

Is there any more information I can provide?

**Comment by directhex** [comment]
Are you adding a _reference_ to the gtk-sharp 2.12.0.0 package (References -> Edit References), or a _NuGet) package reference (Packages -> Add Packages)?

**Comment by define-private-public** [comment]
Okay.  I got a fresh flatpak here is what I see if I create a new Gtk# 2.0 project:

![new-gtk2](https://user-images.githubusercontent.com/4551425/34550920-df32f39c-f0e2-11e7-9ce2-5d6999a4c316.png)

The program does compile and run fine, but those red X's are a little bothersome.  This seems to be using `gtk-sharp` 2.x, and so far it looks like this is the only way to make a Gtk# 2.0 app.  

Now if I create a new console project, then add the `GtkSharp` package from Nuget, for some reason it will build properly and run.  I was able to get the basic window up from this page: http://www.mono-project.com/docs/gui/gtksharp/beginners-guide/  I'm not able to add any references to `gtk-sharp` (the 2.0 package).

Though there doesn't seem to be any Glade options available, or by adding one via References.

This error is also appearing when I hover over some of the code with the later project:

![err](https://user-images.githubusercontent.com/4551425/34550969-54789562-f0e3-11e7-9f8e-be158b4253f8.png)

Is there any other info I can provide?

**Comment by directhex** [comment]
Could you compress your solution directory & attach it? I want to confirm the issue locally, to see what exactly is going wrong. I can't replicate it - but the mention of netstandard is very suspicious

**Comment by define-private-public** [comment]
[Gtk2Test.tar.gz](https://github.com/mono/monodevelop/files/1604984/Gtk2Test.tar.gz)

**Comment by directhex** [comment]
OK, it looks like the NuGet packages in Gtk2Test2 are using NetStandard, and that involves a whole bunch of .NET Core integration I have yet to unravel (it's on my TODO, but not at the top).

I can't see the red X issue in Gtk2Test. Can you hover over a red X with the mouse, to see if it gives a toolip on what it thinks the problem is? Also, be sure to do an update, I've pushed out a couple of new builds within the last week.

![screenshot from 2018-01-05 09-24-49](https://user-images.githubusercontent.com/308992/34613049-4ff3109a-f1fa-11e7-9ee7-5fef1d7202ab.png)

**Comment by define-private-public** [comment]
It's saying "Assembly not found for .NET Framework 4.6.1"

I tried switching it to a few other ones, still no luck for resolving the issue.  Also, I don't seem to be seeing any assemblies that have "Mono," in them; like it used to for the MonoDevelop in the Ubuntu apt repos.  What happened to them?

**Comment by directhex** [comment]
It seems, inadvertently, that your netstandard issue has revealed a bigger class of problem.

Working on a new build, which should resolve it

**Comment by directhex** [comment]
NetStandard 2 projects should no longer throw `Object not defined` build errors.

**Comment by define-private-public** [comment]
I can confirm that `Object no defined` part now.

**Comment by directhex** [comment]
I've finally been able to replicate your issue. Am trying to get help from the VSfM team on fixing it - basically any assembly built without a TargetFramework attribute (any from `make` not `xbuild` or `msbuild`) are excluded from the packages list - and as it happens cache invalidation on the list of offered libs is *also* broken

**Comment by directhex** [comment]
Fixes dispatched for building. Will take a few hours.

You may need to delete `~/.var/app/com.xamarin.MonoDevelop/config/xbuild/pkgconfig-cache-2.xml` to get back into a fixed state, after installing the update.
