### ISSUE TITLE
Failed to authenticate SSH session: Callback returned error

### ISSUE THREAD

**Issue by Aleishus** [mono/monodevelop#6626]
I just regenerate ssh public key on my mac ,then get this error ,the git command works well.

Visual Studio Community 2017 for Mac
Version 7.6.11 (build 9)
Installation UUID: b9997b46-77ae-4c1d-bf7f-0d67670189db
Runtime:
	Mono 5.12.0.309 (2018-02/39d89a335c8) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 4.4.1.178 (master / eeaeb7e6)

	Package version: 512000309

```bash
MonoDevelop.VersionControl.VersionControlException: Failed to authenticate SSH session: Callback returned error ---> LibGit2Sharp.LibGit2SharpException: Failed to authenticate SSH session: Callback returned error
  at LibGit2Sharp.Core.Ensure.HandleError (System.Int32 result) [0x00078] in /Users/vsts/agent/2.141.1/work/1/s/monodevelop/main/external/libgit2sharp/LibGit2Sharp/Core/Ensure.cs:161 
  at LibGit2Sharp.Core.Ensure.ZeroResult (System.Int32 result) [0x00004] in /Users/vsts/agent/2.141.1/work/1/s/monodevelop/main/external/libgit2sharp/LibGit2Sharp/Core/Ensure.cs:179 
  at LibGit2Sharp.Core.Proxy.git_remote_fetch (LibGit2Sharp.Core.Handles.RemoteSafeHandle remote, System.Collections.Generic.IEnumerable`1[T] refSpecs, LibGit2Sharp.Core.GitFetchOptions fetchOptions, System.String logMessage) [0x00023] in /Users/vsts/agent/2.141.1/work/1/s/monodevelop/main/external/libgit2sharp/LibGit2Sharp/Core/Proxy.cs:2118 
  at LibGit2Sharp.Network.DoFetch (LibGit2Sharp.FetchOptions options, LibGit2Sharp.Core.Handles.RemoteSafeHandle remoteHandle, System.String logMessage, System.Collections.Generic.IEnumerable`1[T] refspecs) [0x00055] in /Users/vsts/agent/2.141.1/work/1/s/monodevelop/main/external/libgit2sharp/LibGit2Sharp/Network.cs:209 
  at LibGit2Sharp.Network.DoFetch (LibGit2Sharp.Core.Handles.RepositorySafeHandle repoHandle, LibGit2Sharp.Remote remote, LibGit2Sharp.FetchOptions options, System.String logMessage, System.Collections.Generic.IEnumerable`1[T] refspecs) [0x00008] in /Users/vsts/agent/2.141.1/work/1/s/monodevelop/main/external/libgit2sharp/LibGit2Sharp/Network.cs:164 
  at LibGit2Sharp.Network.Fetch (LibGit2Sharp.Remote remote, LibGit2Sharp.FetchOptions options, System.String logMessage) [0x0000b] in /Users/vsts/agent/2.141.1/work/1/s/monodevelop/main/external/libgit2sharp/LibGit2Sharp/Network.cs:251 
  at LibGit2Sharp.Network.Fetch (LibGit2Sharp.Remote remote, LibGit2Sharp.FetchOptions options) [0x00000] in /Users/vsts/agent/2.141.1/work/1/s/monodevelop/main/external/libgit2sharp/LibGit2Sharp/Network.cs:228 
  at LibGit2Sharp.RepositoryExtensions.Fetch (LibGit2Sharp.IRepository repository, System.String remoteName, LibGit2Sharp.FetchOptions options) [0x00029] in /Users/vsts/agent/2.141.1/work/1/s/monodevelop/main/external/libgit2sharp/LibGit2Sharp/RepositoryExtensions.cs:318 
  at MonoDevelop.VersionControl.Git.GitRepository+<>c__DisplayClass57_0.<Fetch>b__0 (MonoDevelop.VersionControl.Git.GitCredentialsType credType) [0x0000d] in /Users/vsts/agent/2.141.1/work/1/s/monodevelop/main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/GitRepository.cs:668 
  at MonoDevelop.VersionControl.Git.GitRepository.RetryUntilSuccess (MonoDevelop.Core.ProgressMonitor monitor, System.Action`1[T] func, System.Action onRetry) [0x00013] in /Users/vsts/agent/2.141.1/work/1/s/monodevelop/main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/GitRepository.cs:621 
```

> VS bug [#843391](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/843391)

**Comment by GangOfPenguins** [comment]
Having this same issue in Visual Studio for Mac (based on monodevelop).

**Comment by jhessin** [comment]
How do we set our ssh keys?

**Comment by sevoku** [comment]
This is fixed in 8.0: https://github.com/mono/monodevelop/pull/7078, it was an outdated libssh version.

**Comment by sevoku** [comment]
Please reopen, if this still happens on 8.0. Thanks!

**Comment by hasan-sytel** [comment]
This is still happening with VS Mac 8.0.5 (build 9)

**Comment by jsuarezruiz** [comment]
Is still happening with VS Mac 8.0.5: https://developercommunity.visualstudio.com/content/problem/560672/built-in-version-control-can-not-push.html

**Comment by jwu92610** [comment]
The same error is still happening with Visual Studio Professional 2019 for Mac Version 8.1 (build 2742) "Failed to authenticate SSH session: Callback returned error". We have to use some workarounds instead.

**Comment by mkrueger** [comment]
We fixed the issue. 
As a work around for older versions the ssh2 key  can be generated using the PEM format:

ssh-keygen -t rsa -b 4096 -m PEM -C “your@email”

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-37] Comment by **xamarinc**



Fixed in version 8.4.0.554 (master)



Pull Request #8296 merged by: Vsevolod Kukol  
 Author: mono  
 Commit: 1df26ce624a246c67f9f6a376ff447aad5c8a335 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-39] Comment by **xamarinc**



Fixed in version 8.3.0.988 (release-8.3)



Pull Request #8296 merged by: Vsevolod Kukol  
 Author: mono  
 Commit: 1df26ce624a246c67f9f6a376ff447aad5c8a335 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-40] Comment by **xamarinc**



Fixed in version 8.2.3.5 (release-8.2)



Pull Request #8307 merged by: Lluis Sanchez  
 Author: mono  
 Commit: b2ebfa8acc17c3a01d2cb357fedef5ebd9d63db5 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-42] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Pull Request #8296 merged by: Vsevolod Kukol  
 Author: mono  
 Commit: 1df26ce624a246c67f9f6a376ff447aad5c8a335 (xamarin/monodevelop)
